# Generated by Django 5.1 on 2024-08-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good2',
            old_name='message2',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message2',
            old_name='good2_count',
            new_name='good_count',
        ),
    ]
